import ProductCard from '@/components/website/Card';
import { getProducts } from '@/library/api-call';
import { imageConfigDefault } from 'next/dist/shared/lib/image-config';
import React, {  } from 'react'
export const metadata = {
  title: "ShopLogo Store",
  description: "Generated by create next app",
};

export default async function page({}) {

  const product = await getProducts();
  // console.log(product)
  const data = product.data

  return (
    <>


      <div className='grid grid-cols-3 space-x-5 gap-5'>
        {
          data.map((product)=>{
            return <ProductCard product={product} key={product._id}/>
          })
        }
      </div>
    </>
  )
}
