import ProductCard from '@/components/website/Card';
import { getProducts } from '@/library/api-call';
import React, { use } from 'react'

export const metadata = {
  title: "ShopLogo Store",
  description: "Generated by create next app",
};

export default async function page({ params , searchParams}) {
  const resolvedSearchParams = await searchParams; // Await searchParams


    const color = resolvedSearchParams.color || null 
    const brand = resolvedSearchParams.brand || null
        const min = resolvedSearchParams?.min || null
    const max = resolvedSearchParams?.max || null

  const category_slug = params.category_slug;
  const product = await getProducts(null, category_slug , color, brand , min, max);
  const data = product?.data || [];

  return (
    <>


      <div className='grid grid-cols-3 space-x-5 gap-5'>
        {
          data.map((product) => {
            return <ProductCard product={product} key={product._id} />
          })
        }
      </div>
    </>
  )
}
