import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideMenu from "@/components/admin/SideMenu";
import Header from "@/components/admin/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="flex">
          <SideMenu />
          <div className="flex-1 p-2">
          {children}
          </div>
        </div>

      </body>
    </html>
  );
}
